namespace YantraJS.Core.FastParser
{
    public static class HiddenTokens
    {
        public const int Operator = 0b0100000;
    }

    /// <summary>
    /// Tokens should be arranged in order of precedence
    /// </summary>
    public enum TokenTypes
    {
        Empty = 0,
        // Operator       = 0b0100000,
        // AssignOperator = 0b1000000,
        SquareBracketStart,
        SquareBracketEnd,
        CurlyBracketStart,
        CurlyBracketEnd,
        TemplateBegin,
        TemplatePart,
        TemplateEnd,
        LineTerminator,
        None,
        SemiColon,
        EOF,
        Identifier,
        Number,
        String,
        BracketEnd,
        BracketStart,
        StrictlyEqual,
        Equal,
        Lambda,
        Assign,
        AssignMultiply,
        AssignDivide,
        AssignAdd,
        AssignSubtract,
        AssignUnsignedRightShift,
        AssignBitwideAnd,
        AssignBitwideOr,
        AssignRightShift,
        AssignLeftShift,
        AssignPower,
        StrictlyNotEqual,
        NotEqual,
        Negate,
        RightShift,
        UnsignedRightShift,
        GreaterOrEqual,
        Greater,
        LeftShift,
        LessOrEqual,
        Less,
        Multiply,
        Divide,
        Power,
        BitwiseAnd,
        BooleanAnd,
        BooleanOr,
        BitwiseOr,
        Increment,
        Plus,
        Decrement,
        Minus,
        AssignXor,
        Xor,
        QuestionMark,
        Colon,
        BitwiseNot,
        AssignMod,
        Mod,
        Comma,
        QuestionDot,
        Dot,
        TripleDots,
        Null,
        False,
        True,
        Hash,
        RegExLiteral,
        InstanceOf,
        In,
    }
}
