var x = {};

(function (SyntaxKind) {
    SyntaxKind[SyntaxKind['Unknown'] = 0] = 'Unknown';
    SyntaxKind[SyntaxKind['EndOfFileToken'] = 1] = 'EndOfFileToken';
    SyntaxKind[SyntaxKind['SingleLineCommentTrivia'] = 2] = 'SingleLineCommentTrivia';
    SyntaxKind[SyntaxKind['MultiLineCommentTrivia'] = 3] = 'MultiLineCommentTrivia';
    SyntaxKind[SyntaxKind['NewLineTrivia'] = 4] = 'NewLineTrivia';
    SyntaxKind[SyntaxKind['WhitespaceTrivia'] = 5] = 'WhitespaceTrivia';
    // We detect and preserve #! on the first line
    SyntaxKind[SyntaxKind['ShebangTrivia'] = 6] = 'ShebangTrivia';
    // We detect and provide better error recovery when we encounter a git merge marker.  This
    // allows us to edit files with git-conflict markers in them in a much more pleasant manner.
    SyntaxKind[SyntaxKind['ConflictMarkerTrivia'] = 7] = 'ConflictMarkerTrivia';
    // Literals
    SyntaxKind[SyntaxKind['NumericLiteral'] = 8] = 'NumericLiteral';
    SyntaxKind[SyntaxKind['BigIntLiteral'] = 9] = 'BigIntLiteral';
    SyntaxKind[SyntaxKind['StringLiteral'] = 10] = 'StringLiteral';
    SyntaxKind[SyntaxKind['JsxText'] = 11] = 'JsxText';
    SyntaxKind[SyntaxKind['JsxTextAllWhiteSpaces'] = 12] = 'JsxTextAllWhiteSpaces';
    SyntaxKind[SyntaxKind['RegularExpressionLiteral'] = 13] = 'RegularExpressionLiteral';
    SyntaxKind[SyntaxKind['NoSubstitutionTemplateLiteral'] = 14] = 'NoSubstitutionTemplateLiteral';
    // Pseudo-literals
    SyntaxKind[SyntaxKind['TemplateHead'] = 15] = 'TemplateHead';
    SyntaxKind[SyntaxKind['TemplateMiddle'] = 16] = 'TemplateMiddle';
    SyntaxKind[SyntaxKind['TemplateTail'] = 17] = 'TemplateTail';
    // Punctuation
    SyntaxKind[SyntaxKind['OpenBraceToken'] = 18] = 'OpenBraceToken';
    SyntaxKind[SyntaxKind['CloseBraceToken'] = 19] = 'CloseBraceToken';
    SyntaxKind[SyntaxKind['OpenParenToken'] = 20] = 'OpenParenToken';
    SyntaxKind[SyntaxKind['CloseParenToken'] = 21] = 'CloseParenToken';
    SyntaxKind[SyntaxKind['OpenBracketToken'] = 22] = 'OpenBracketToken';
    SyntaxKind[SyntaxKind['CloseBracketToken'] = 23] = 'CloseBracketToken';
    SyntaxKind[SyntaxKind['DotToken'] = 24] = 'DotToken';
    SyntaxKind[SyntaxKind['DotDotDotToken'] = 25] = 'DotDotDotToken';
    SyntaxKind[SyntaxKind['SemicolonToken'] = 26] = 'SemicolonToken';
    SyntaxKind[SyntaxKind['CommaToken'] = 27] = 'CommaToken';
    SyntaxKind[SyntaxKind['QuestionDotToken'] = 28] = 'QuestionDotToken';
    SyntaxKind[SyntaxKind['LessThanToken'] = 29] = 'LessThanToken';
    SyntaxKind[SyntaxKind['LessThanSlashToken'] = 30] = 'LessThanSlashToken';
    SyntaxKind[SyntaxKind['GreaterThanToken'] = 31] = 'GreaterThanToken';
    SyntaxKind[SyntaxKind['LessThanEqualsToken'] = 32] = 'LessThanEqualsToken';
    SyntaxKind[SyntaxKind['GreaterThanEqualsToken'] = 33] = 'GreaterThanEqualsToken';
    SyntaxKind[SyntaxKind['EqualsEqualsToken'] = 34] = 'EqualsEqualsToken';
    SyntaxKind[SyntaxKind['ExclamationEqualsToken'] = 35] = 'ExclamationEqualsToken';
    SyntaxKind[SyntaxKind['EqualsEqualsEqualsToken'] = 36] = 'EqualsEqualsEqualsToken';
    SyntaxKind[SyntaxKind['ExclamationEqualsEqualsToken'] = 37] = 'ExclamationEqualsEqualsToken';
    SyntaxKind[SyntaxKind['EqualsGreaterThanToken'] = 38] = 'EqualsGreaterThanToken';
    SyntaxKind[SyntaxKind['PlusToken'] = 39] = 'PlusToken';
    SyntaxKind[SyntaxKind['MinusToken'] = 40] = 'MinusToken';
    SyntaxKind[SyntaxKind['AsteriskToken'] = 41] = 'AsteriskToken';
    SyntaxKind[SyntaxKind['AsteriskAsteriskToken'] = 42] = 'AsteriskAsteriskToken';
    SyntaxKind[SyntaxKind['SlashToken'] = 43] = 'SlashToken';
    SyntaxKind[SyntaxKind['PercentToken'] = 44] = 'PercentToken';
    SyntaxKind[SyntaxKind['PlusPlusToken'] = 45] = 'PlusPlusToken';
    SyntaxKind[SyntaxKind['MinusMinusToken'] = 46] = 'MinusMinusToken';
    SyntaxKind[SyntaxKind['LessThanLessThanToken'] = 47] = 'LessThanLessThanToken';
    SyntaxKind[SyntaxKind['GreaterThanGreaterThanToken'] = 48] = 'GreaterThanGreaterThanToken';
    SyntaxKind[SyntaxKind['GreaterThanGreaterThanGreaterThanToken'] = 49] = 'GreaterThanGreaterThanGreaterThanToken';
    SyntaxKind[SyntaxKind['AmpersandToken'] = 50] = 'AmpersandToken';
    SyntaxKind[SyntaxKind['BarToken'] = 51] = 'BarToken';
    SyntaxKind[SyntaxKind['CaretToken'] = 52] = 'CaretToken';
    SyntaxKind[SyntaxKind['ExclamationToken'] = 53] = 'ExclamationToken';
    SyntaxKind[SyntaxKind['TildeToken'] = 54] = 'TildeToken';
    SyntaxKind[SyntaxKind['AmpersandAmpersandToken'] = 55] = 'AmpersandAmpersandToken';
    SyntaxKind[SyntaxKind['BarBarToken'] = 56] = 'BarBarToken';
    SyntaxKind[SyntaxKind['QuestionToken'] = 57] = 'QuestionToken';
    SyntaxKind[SyntaxKind['ColonToken'] = 58] = 'ColonToken';
    SyntaxKind[SyntaxKind['AtToken'] = 59] = 'AtToken';
    SyntaxKind[SyntaxKind['QuestionQuestionToken'] = 60] = 'QuestionQuestionToken';
    /** Only the JSDoc scanner produces BacktickToken. The normal scanner produces NoSubstitutionTemplateLiteral and related kinds. */
    SyntaxKind[SyntaxKind['BacktickToken'] = 61] = 'BacktickToken';
    // Assignments
    SyntaxKind[SyntaxKind['EqualsToken'] = 62] = 'EqualsToken';
    SyntaxKind[SyntaxKind['PlusEqualsToken'] = 63] = 'PlusEqualsToken';
    SyntaxKind[SyntaxKind['MinusEqualsToken'] = 64] = 'MinusEqualsToken';
    SyntaxKind[SyntaxKind['AsteriskEqualsToken'] = 65] = 'AsteriskEqualsToken';
    SyntaxKind[SyntaxKind['AsteriskAsteriskEqualsToken'] = 66] = 'AsteriskAsteriskEqualsToken';
    SyntaxKind[SyntaxKind['SlashEqualsToken'] = 67] = 'SlashEqualsToken';
    SyntaxKind[SyntaxKind['PercentEqualsToken'] = 68] = 'PercentEqualsToken';
    SyntaxKind[SyntaxKind['LessThanLessThanEqualsToken'] = 69] = 'LessThanLessThanEqualsToken';
    SyntaxKind[SyntaxKind['GreaterThanGreaterThanEqualsToken'] = 70] = 'GreaterThanGreaterThanEqualsToken';
    SyntaxKind[SyntaxKind['GreaterThanGreaterThanGreaterThanEqualsToken'] = 71] = 'GreaterThanGreaterThanGreaterThanEqualsToken';
    SyntaxKind[SyntaxKind['AmpersandEqualsToken'] = 72] = 'AmpersandEqualsToken';
    SyntaxKind[SyntaxKind['BarEqualsToken'] = 73] = 'BarEqualsToken';
    SyntaxKind[SyntaxKind['BarBarEqualsToken'] = 74] = 'BarBarEqualsToken';
    SyntaxKind[SyntaxKind['AmpersandAmpersandEqualsToken'] = 75] = 'AmpersandAmpersandEqualsToken';
    SyntaxKind[SyntaxKind['QuestionQuestionEqualsToken'] = 76] = 'QuestionQuestionEqualsToken';
    SyntaxKind[SyntaxKind['CaretEqualsToken'] = 77] = 'CaretEqualsToken';
    // Identifiers and PrivateIdentifiers
    SyntaxKind[SyntaxKind['Identifier'] = 78] = 'Identifier';
    SyntaxKind[SyntaxKind['PrivateIdentifier'] = 79] = 'PrivateIdentifier';
    // Reserved words
    SyntaxKind[SyntaxKind['BreakKeyword'] = 80] = 'BreakKeyword';
    SyntaxKind[SyntaxKind['CaseKeyword'] = 81] = 'CaseKeyword';
    SyntaxKind[SyntaxKind['CatchKeyword'] = 82] = 'CatchKeyword';
    SyntaxKind[SyntaxKind['ClassKeyword'] = 83] = 'ClassKeyword';
    SyntaxKind[SyntaxKind['ConstKeyword'] = 84] = 'ConstKeyword';
    SyntaxKind[SyntaxKind['ContinueKeyword'] = 85] = 'ContinueKeyword';
    SyntaxKind[SyntaxKind['DebuggerKeyword'] = 86] = 'DebuggerKeyword';
    SyntaxKind[SyntaxKind['DefaultKeyword'] = 87] = 'DefaultKeyword';
    SyntaxKind[SyntaxKind['DeleteKeyword'] = 88] = 'DeleteKeyword';
    SyntaxKind[SyntaxKind['DoKeyword'] = 89] = 'DoKeyword';
    SyntaxKind[SyntaxKind['ElseKeyword'] = 90] = 'ElseKeyword';
    SyntaxKind[SyntaxKind['EnumKeyword'] = 91] = 'EnumKeyword';
    SyntaxKind[SyntaxKind['ExportKeyword'] = 92] = 'ExportKeyword';
    SyntaxKind[SyntaxKind['ExtendsKeyword'] = 93] = 'ExtendsKeyword';
    SyntaxKind[SyntaxKind['FalseKeyword'] = 94] = 'FalseKeyword';
    SyntaxKind[SyntaxKind['FinallyKeyword'] = 95] = 'FinallyKeyword';
    SyntaxKind[SyntaxKind['ForKeyword'] = 96] = 'ForKeyword';
    SyntaxKind[SyntaxKind['FunctionKeyword'] = 97] = 'FunctionKeyword';
    SyntaxKind[SyntaxKind['IfKeyword'] = 98] = 'IfKeyword';
    SyntaxKind[SyntaxKind['ImportKeyword'] = 99] = 'ImportKeyword';
    SyntaxKind[SyntaxKind['InKeyword'] = 100] = 'InKeyword';
    SyntaxKind[SyntaxKind['InstanceOfKeyword'] = 101] = 'InstanceOfKeyword';
    SyntaxKind[SyntaxKind['NewKeyword'] = 102] = 'NewKeyword';
    SyntaxKind[SyntaxKind['NullKeyword'] = 103] = 'NullKeyword';
    SyntaxKind[SyntaxKind['ReturnKeyword'] = 104] = 'ReturnKeyword';
    SyntaxKind[SyntaxKind['SuperKeyword'] = 105] = 'SuperKeyword';
    SyntaxKind[SyntaxKind['SwitchKeyword'] = 106] = 'SwitchKeyword';
    SyntaxKind[SyntaxKind['ThisKeyword'] = 107] = 'ThisKeyword';
    SyntaxKind[SyntaxKind['ThrowKeyword'] = 108] = 'ThrowKeyword';
    SyntaxKind[SyntaxKind['TrueKeyword'] = 109] = 'TrueKeyword';
    SyntaxKind[SyntaxKind['TryKeyword'] = 110] = 'TryKeyword';
    SyntaxKind[SyntaxKind['TypeOfKeyword'] = 111] = 'TypeOfKeyword';
    SyntaxKind[SyntaxKind['VarKeyword'] = 112] = 'VarKeyword';
    SyntaxKind[SyntaxKind['VoidKeyword'] = 113] = 'VoidKeyword';
    SyntaxKind[SyntaxKind['WhileKeyword'] = 114] = 'WhileKeyword';
    SyntaxKind[SyntaxKind['WithKeyword'] = 115] = 'WithKeyword';
    // Strict mode reserved words
    SyntaxKind[SyntaxKind['ImplementsKeyword'] = 116] = 'ImplementsKeyword';
    SyntaxKind[SyntaxKind['InterfaceKeyword'] = 117] = 'InterfaceKeyword';
    SyntaxKind[SyntaxKind['LetKeyword'] = 118] = 'LetKeyword';
    SyntaxKind[SyntaxKind['PackageKeyword'] = 119] = 'PackageKeyword';
    SyntaxKind[SyntaxKind['PrivateKeyword'] = 120] = 'PrivateKeyword';
    SyntaxKind[SyntaxKind['ProtectedKeyword'] = 121] = 'ProtectedKeyword';
    SyntaxKind[SyntaxKind['PublicKeyword'] = 122] = 'PublicKeyword';
    SyntaxKind[SyntaxKind['StaticKeyword'] = 123] = 'StaticKeyword';
    SyntaxKind[SyntaxKind['YieldKeyword'] = 124] = 'YieldKeyword';
    // Contextual keywords
    SyntaxKind[SyntaxKind['AbstractKeyword'] = 125] = 'AbstractKeyword';
    SyntaxKind[SyntaxKind['AsKeyword'] = 126] = 'AsKeyword';
    SyntaxKind[SyntaxKind['AssertsKeyword'] = 127] = 'AssertsKeyword';
    SyntaxKind[SyntaxKind['AnyKeyword'] = 128] = 'AnyKeyword';
    SyntaxKind[SyntaxKind['AsyncKeyword'] = 129] = 'AsyncKeyword';
    SyntaxKind[SyntaxKind['AwaitKeyword'] = 130] = 'AwaitKeyword';
    SyntaxKind[SyntaxKind['BooleanKeyword'] = 131] = 'BooleanKeyword';
    SyntaxKind[SyntaxKind['ConstructorKeyword'] = 132] = 'ConstructorKeyword';
    SyntaxKind[SyntaxKind['DeclareKeyword'] = 133] = 'DeclareKeyword';
    SyntaxKind[SyntaxKind['GetKeyword'] = 134] = 'GetKeyword';
    SyntaxKind[SyntaxKind['InferKeyword'] = 135] = 'InferKeyword';
    SyntaxKind[SyntaxKind['IsKeyword'] = 136] = 'IsKeyword';
    SyntaxKind[SyntaxKind['KeyOfKeyword'] = 137] = 'KeyOfKeyword';
    SyntaxKind[SyntaxKind['ModuleKeyword'] = 138] = 'ModuleKeyword';
    SyntaxKind[SyntaxKind['NamespaceKeyword'] = 139] = 'NamespaceKeyword';
    SyntaxKind[SyntaxKind['NeverKeyword'] = 140] = 'NeverKeyword';
    SyntaxKind[SyntaxKind['ReadonlyKeyword'] = 141] = 'ReadonlyKeyword';
    SyntaxKind[SyntaxKind['RequireKeyword'] = 142] = 'RequireKeyword';
    SyntaxKind[SyntaxKind['NumberKeyword'] = 143] = 'NumberKeyword';
    SyntaxKind[SyntaxKind['ObjectKeyword'] = 144] = 'ObjectKeyword';
    SyntaxKind[SyntaxKind['SetKeyword'] = 145] = 'SetKeyword';
    SyntaxKind[SyntaxKind['StringKeyword'] = 146] = 'StringKeyword';
    SyntaxKind[SyntaxKind['SymbolKeyword'] = 147] = 'SymbolKeyword';
    SyntaxKind[SyntaxKind['TypeKeyword'] = 148] = 'TypeKeyword';
    SyntaxKind[SyntaxKind['UndefinedKeyword'] = 149] = 'UndefinedKeyword';
    SyntaxKind[SyntaxKind['UniqueKeyword'] = 150] = 'UniqueKeyword';
    SyntaxKind[SyntaxKind['UnknownKeyword'] = 151] = 'UnknownKeyword';
    SyntaxKind[SyntaxKind['FromKeyword'] = 152] = 'FromKeyword';
    SyntaxKind[SyntaxKind['GlobalKeyword'] = 153] = 'GlobalKeyword';
    SyntaxKind[SyntaxKind['BigIntKeyword'] = 154] = 'BigIntKeyword';
    SyntaxKind[SyntaxKind['OfKeyword'] = 155] = 'OfKeyword';
    // Parse tree nodes
    // Names
    SyntaxKind[SyntaxKind['QualifiedName'] = 156] = 'QualifiedName';
    SyntaxKind[SyntaxKind['ComputedPropertyName'] = 157] = 'ComputedPropertyName';
    // Signature elements
    SyntaxKind[SyntaxKind['TypeParameter'] = 158] = 'TypeParameter';
    SyntaxKind[SyntaxKind['Parameter'] = 159] = 'Parameter';
    SyntaxKind[SyntaxKind['Decorator'] = 160] = 'Decorator';
    // TypeMember
    SyntaxKind[SyntaxKind['PropertySignature'] = 161] = 'PropertySignature';
    SyntaxKind[SyntaxKind['PropertyDeclaration'] = 162] = 'PropertyDeclaration';
    SyntaxKind[SyntaxKind['MethodSignature'] = 163] = 'MethodSignature';
    SyntaxKind[SyntaxKind['MethodDeclaration'] = 164] = 'MethodDeclaration';
    SyntaxKind[SyntaxKind['Constructor'] = 165] = 'Constructor';
    SyntaxKind[SyntaxKind['GetAccessor'] = 166] = 'GetAccessor';
    SyntaxKind[SyntaxKind['SetAccessor'] = 167] = 'SetAccessor';
    SyntaxKind[SyntaxKind['CallSignature'] = 168] = 'CallSignature';
    SyntaxKind[SyntaxKind['ConstructSignature'] = 169] = 'ConstructSignature';
    SyntaxKind[SyntaxKind['IndexSignature'] = 170] = 'IndexSignature';
    // Type
    SyntaxKind[SyntaxKind['TypePredicate'] = 171] = 'TypePredicate';
    SyntaxKind[SyntaxKind['TypeReference'] = 172] = 'TypeReference';
    SyntaxKind[SyntaxKind['FunctionType'] = 173] = 'FunctionType';
    SyntaxKind[SyntaxKind['ConstructorType'] = 174] = 'ConstructorType';
    SyntaxKind[SyntaxKind['TypeQuery'] = 175] = 'TypeQuery';
    SyntaxKind[SyntaxKind['TypeLiteral'] = 176] = 'TypeLiteral';
    SyntaxKind[SyntaxKind['ArrayType'] = 177] = 'ArrayType';
    SyntaxKind[SyntaxKind['TupleType'] = 178] = 'TupleType';
    SyntaxKind[SyntaxKind['OptionalType'] = 179] = 'OptionalType';
    SyntaxKind[SyntaxKind['RestType'] = 180] = 'RestType';
    SyntaxKind[SyntaxKind['UnionType'] = 181] = 'UnionType';
    SyntaxKind[SyntaxKind['IntersectionType'] = 182] = 'IntersectionType';
    SyntaxKind[SyntaxKind['ConditionalType'] = 183] = 'ConditionalType';
    SyntaxKind[SyntaxKind['InferType'] = 184] = 'InferType';
    SyntaxKind[SyntaxKind['ParenthesizedType'] = 185] = 'ParenthesizedType';
    SyntaxKind[SyntaxKind['ThisType'] = 186] = 'ThisType';
    SyntaxKind[SyntaxKind['TypeOperator'] = 187] = 'TypeOperator';
    SyntaxKind[SyntaxKind['IndexedAccessType'] = 188] = 'IndexedAccessType';
    SyntaxKind[SyntaxKind['MappedType'] = 189] = 'MappedType';
    SyntaxKind[SyntaxKind['LiteralType'] = 190] = 'LiteralType';
    SyntaxKind[SyntaxKind['NamedTupleMember'] = 191] = 'NamedTupleMember';
    SyntaxKind[SyntaxKind['ImportType'] = 192] = 'ImportType';
    // Binding patterns
    SyntaxKind[SyntaxKind['ObjectBindingPattern'] = 193] = 'ObjectBindingPattern';
    SyntaxKind[SyntaxKind['ArrayBindingPattern'] = 194] = 'ArrayBindingPattern';
    SyntaxKind[SyntaxKind['BindingElement'] = 195] = 'BindingElement';
    // Expression
    SyntaxKind[SyntaxKind['ArrayLiteralExpression'] = 196] = 'ArrayLiteralExpression';
    SyntaxKind[SyntaxKind['ObjectLiteralExpression'] = 197] = 'ObjectLiteralExpression';
    SyntaxKind[SyntaxKind['PropertyAccessExpression'] = 198] = 'PropertyAccessExpression';
    SyntaxKind[SyntaxKind['ElementAccessExpression'] = 199] = 'ElementAccessExpression';
    SyntaxKind[SyntaxKind['CallExpression'] = 200] = 'CallExpression';
    SyntaxKind[SyntaxKind['NewExpression'] = 201] = 'NewExpression';
    SyntaxKind[SyntaxKind['TaggedTemplateExpression'] = 202] = 'TaggedTemplateExpression';
    SyntaxKind[SyntaxKind['TypeAssertionExpression'] = 203] = 'TypeAssertionExpression';
    SyntaxKind[SyntaxKind['ParenthesizedExpression'] = 204] = 'ParenthesizedExpression';
    SyntaxKind[SyntaxKind['FunctionExpression'] = 205] = 'FunctionExpression';
    SyntaxKind[SyntaxKind['ArrowFunction'] = 206] = 'ArrowFunction';
    SyntaxKind[SyntaxKind['DeleteExpression'] = 207] = 'DeleteExpression';
    SyntaxKind[SyntaxKind['TypeOfExpression'] = 208] = 'TypeOfExpression';
    SyntaxKind[SyntaxKind['VoidExpression'] = 209] = 'VoidExpression';
    SyntaxKind[SyntaxKind['AwaitExpression'] = 210] = 'AwaitExpression';
    SyntaxKind[SyntaxKind['PrefixUnaryExpression'] = 211] = 'PrefixUnaryExpression';
    SyntaxKind[SyntaxKind['PostfixUnaryExpression'] = 212] = 'PostfixUnaryExpression';
    SyntaxKind[SyntaxKind['BinaryExpression'] = 213] = 'BinaryExpression';
    SyntaxKind[SyntaxKind['ConditionalExpression'] = 214] = 'ConditionalExpression';
    SyntaxKind[SyntaxKind['TemplateExpression'] = 215] = 'TemplateExpression';
    SyntaxKind[SyntaxKind['YieldExpression'] = 216] = 'YieldExpression';
    SyntaxKind[SyntaxKind['SpreadElement'] = 217] = 'SpreadElement';
    SyntaxKind[SyntaxKind['ClassExpression'] = 218] = 'ClassExpression';
    SyntaxKind[SyntaxKind['OmittedExpression'] = 219] = 'OmittedExpression';
    SyntaxKind[SyntaxKind['ExpressionWithTypeArguments'] = 220] = 'ExpressionWithTypeArguments';
    SyntaxKind[SyntaxKind['AsExpression'] = 221] = 'AsExpression';
    SyntaxKind[SyntaxKind['NonNullExpression'] = 222] = 'NonNullExpression';
    SyntaxKind[SyntaxKind['MetaProperty'] = 223] = 'MetaProperty';
    SyntaxKind[SyntaxKind['SyntheticExpression'] = 224] = 'SyntheticExpression';
    // Misc
    SyntaxKind[SyntaxKind['TemplateSpan'] = 225] = 'TemplateSpan';
    SyntaxKind[SyntaxKind['SemicolonClassElement'] = 226] = 'SemicolonClassElement';
    // Element
    SyntaxKind[SyntaxKind['Block'] = 227] = 'Block';
    SyntaxKind[SyntaxKind['EmptyStatement'] = 228] = 'EmptyStatement';
    SyntaxKind[SyntaxKind['VariableStatement'] = 229] = 'VariableStatement';
    SyntaxKind[SyntaxKind['ExpressionStatement'] = 230] = 'ExpressionStatement';
    SyntaxKind[SyntaxKind['IfStatement'] = 231] = 'IfStatement';
    SyntaxKind[SyntaxKind['DoStatement'] = 232] = 'DoStatement';
    SyntaxKind[SyntaxKind['WhileStatement'] = 233] = 'WhileStatement';
    SyntaxKind[SyntaxKind['ForStatement'] = 234] = 'ForStatement';
    SyntaxKind[SyntaxKind['ForInStatement'] = 235] = 'ForInStatement';
    SyntaxKind[SyntaxKind['ForOfStatement'] = 236] = 'ForOfStatement';
    SyntaxKind[SyntaxKind['ContinueStatement'] = 237] = 'ContinueStatement';
    SyntaxKind[SyntaxKind['BreakStatement'] = 238] = 'BreakStatement';
    SyntaxKind[SyntaxKind['ReturnStatement'] = 239] = 'ReturnStatement';
    SyntaxKind[SyntaxKind['WithStatement'] = 240] = 'WithStatement';
    SyntaxKind[SyntaxKind['SwitchStatement'] = 241] = 'SwitchStatement';
    SyntaxKind[SyntaxKind['LabeledStatement'] = 242] = 'LabeledStatement';
    SyntaxKind[SyntaxKind['ThrowStatement'] = 243] = 'ThrowStatement';
    SyntaxKind[SyntaxKind['TryStatement'] = 244] = 'TryStatement';
    SyntaxKind[SyntaxKind['DebuggerStatement'] = 245] = 'DebuggerStatement';
    SyntaxKind[SyntaxKind['VariableDeclaration'] = 246] = 'VariableDeclaration';
    SyntaxKind[SyntaxKind['VariableDeclarationList'] = 247] = 'VariableDeclarationList';
    SyntaxKind[SyntaxKind['FunctionDeclaration'] = 248] = 'FunctionDeclaration';
    SyntaxKind[SyntaxKind['ClassDeclaration'] = 249] = 'ClassDeclaration';
    SyntaxKind[SyntaxKind['InterfaceDeclaration'] = 250] = 'InterfaceDeclaration';
    SyntaxKind[SyntaxKind['TypeAliasDeclaration'] = 251] = 'TypeAliasDeclaration';
    SyntaxKind[SyntaxKind['EnumDeclaration'] = 252] = 'EnumDeclaration';
    SyntaxKind[SyntaxKind['ModuleDeclaration'] = 253] = 'ModuleDeclaration';
    SyntaxKind[SyntaxKind['ModuleBlock'] = 254] = 'ModuleBlock';
    SyntaxKind[SyntaxKind['CaseBlock'] = 255] = 'CaseBlock';
    SyntaxKind[SyntaxKind['NamespaceExportDeclaration'] = 256] = 'NamespaceExportDeclaration';
    SyntaxKind[SyntaxKind['ImportEqualsDeclaration'] = 257] = 'ImportEqualsDeclaration';
    SyntaxKind[SyntaxKind['ImportDeclaration'] = 258] = 'ImportDeclaration';
    SyntaxKind[SyntaxKind['ImportClause'] = 259] = 'ImportClause';
    SyntaxKind[SyntaxKind['NamespaceImport'] = 260] = 'NamespaceImport';
    SyntaxKind[SyntaxKind['NamedImports'] = 261] = 'NamedImports';
    SyntaxKind[SyntaxKind['ImportSpecifier'] = 262] = 'ImportSpecifier';
    SyntaxKind[SyntaxKind['ExportAssignment'] = 263] = 'ExportAssignment';
    SyntaxKind[SyntaxKind['ExportDeclaration'] = 264] = 'ExportDeclaration';
    SyntaxKind[SyntaxKind['NamedExports'] = 265] = 'NamedExports';
    SyntaxKind[SyntaxKind['NamespaceExport'] = 266] = 'NamespaceExport';
    SyntaxKind[SyntaxKind['ExportSpecifier'] = 267] = 'ExportSpecifier';
    SyntaxKind[SyntaxKind['MissingDeclaration'] = 268] = 'MissingDeclaration';
    // Module references
    SyntaxKind[SyntaxKind['ExternalModuleReference'] = 269] = 'ExternalModuleReference';
    // JSX
    SyntaxKind[SyntaxKind['JsxElement'] = 270] = 'JsxElement';
    SyntaxKind[SyntaxKind['JsxSelfClosingElement'] = 271] = 'JsxSelfClosingElement';
    SyntaxKind[SyntaxKind['JsxOpeningElement'] = 272] = 'JsxOpeningElement';
    SyntaxKind[SyntaxKind['JsxClosingElement'] = 273] = 'JsxClosingElement';
    SyntaxKind[SyntaxKind['JsxFragment'] = 274] = 'JsxFragment';
    SyntaxKind[SyntaxKind['JsxOpeningFragment'] = 275] = 'JsxOpeningFragment';
    SyntaxKind[SyntaxKind['JsxClosingFragment'] = 276] = 'JsxClosingFragment';
    SyntaxKind[SyntaxKind['JsxAttribute'] = 277] = 'JsxAttribute';
    SyntaxKind[SyntaxKind['JsxAttributes'] = 278] = 'JsxAttributes';
    SyntaxKind[SyntaxKind['JsxSpreadAttribute'] = 279] = 'JsxSpreadAttribute';
    SyntaxKind[SyntaxKind['JsxExpression'] = 280] = 'JsxExpression';
    // Clauses
    SyntaxKind[SyntaxKind['CaseClause'] = 281] = 'CaseClause';
    SyntaxKind[SyntaxKind['DefaultClause'] = 282] = 'DefaultClause';
    SyntaxKind[SyntaxKind['HeritageClause'] = 283] = 'HeritageClause';
    SyntaxKind[SyntaxKind['CatchClause'] = 284] = 'CatchClause';
    // Property assignments
    SyntaxKind[SyntaxKind['PropertyAssignment'] = 285] = 'PropertyAssignment';
    SyntaxKind[SyntaxKind['ShorthandPropertyAssignment'] = 286] = 'ShorthandPropertyAssignment';
    SyntaxKind[SyntaxKind['SpreadAssignment'] = 287] = 'SpreadAssignment';
    // Enum
    SyntaxKind[SyntaxKind['EnumMember'] = 288] = 'EnumMember';
    // Unparsed
    SyntaxKind[SyntaxKind['UnparsedPrologue'] = 289] = 'UnparsedPrologue';
    SyntaxKind[SyntaxKind['UnparsedPrepend'] = 290] = 'UnparsedPrepend';
    SyntaxKind[SyntaxKind['UnparsedText'] = 291] = 'UnparsedText';
    SyntaxKind[SyntaxKind['UnparsedInternalText'] = 292] = 'UnparsedInternalText';
    SyntaxKind[SyntaxKind['UnparsedSyntheticReference'] = 293] = 'UnparsedSyntheticReference';
    // Top-level nodes
    SyntaxKind[SyntaxKind['SourceFile'] = 294] = 'SourceFile';
    SyntaxKind[SyntaxKind['Bundle'] = 295] = 'Bundle';
    SyntaxKind[SyntaxKind['UnparsedSource'] = 296] = 'UnparsedSource';
    SyntaxKind[SyntaxKind['InputFiles'] = 297] = 'InputFiles';
    // JSDoc nodes
    SyntaxKind[SyntaxKind['JSDocTypeExpression'] = 298] = 'JSDocTypeExpression';
    // The * type
    SyntaxKind[SyntaxKind['JSDocAllType'] = 299] = 'JSDocAllType';
    // The ? type
    SyntaxKind[SyntaxKind['JSDocUnknownType'] = 300] = 'JSDocUnknownType';
    SyntaxKind[SyntaxKind['JSDocNullableType'] = 301] = 'JSDocNullableType';
    SyntaxKind[SyntaxKind['JSDocNonNullableType'] = 302] = 'JSDocNonNullableType';
    SyntaxKind[SyntaxKind['JSDocOptionalType'] = 303] = 'JSDocOptionalType';
    SyntaxKind[SyntaxKind['JSDocFunctionType'] = 304] = 'JSDocFunctionType';
    SyntaxKind[SyntaxKind['JSDocVariadicType'] = 305] = 'JSDocVariadicType';
    // https://jsdoc.app/about-namepaths.html
    SyntaxKind[SyntaxKind['JSDocNamepathType'] = 306] = 'JSDocNamepathType';
    SyntaxKind[SyntaxKind['JSDocComment'] = 307] = 'JSDocComment';
    SyntaxKind[SyntaxKind['JSDocTypeLiteral'] = 308] = 'JSDocTypeLiteral';
    SyntaxKind[SyntaxKind['JSDocSignature'] = 309] = 'JSDocSignature';
    SyntaxKind[SyntaxKind['JSDocTag'] = 310] = 'JSDocTag';
    SyntaxKind[SyntaxKind['JSDocAugmentsTag'] = 311] = 'JSDocAugmentsTag';
    SyntaxKind[SyntaxKind['JSDocImplementsTag'] = 312] = 'JSDocImplementsTag';
    SyntaxKind[SyntaxKind['JSDocAuthorTag'] = 313] = 'JSDocAuthorTag';
    SyntaxKind[SyntaxKind['JSDocDeprecatedTag'] = 314] = 'JSDocDeprecatedTag';
    SyntaxKind[SyntaxKind['JSDocClassTag'] = 315] = 'JSDocClassTag';
    SyntaxKind[SyntaxKind['JSDocPublicTag'] = 316] = 'JSDocPublicTag';
    SyntaxKind[SyntaxKind['JSDocPrivateTag'] = 317] = 'JSDocPrivateTag';
    SyntaxKind[SyntaxKind['JSDocProtectedTag'] = 318] = 'JSDocProtectedTag';
    SyntaxKind[SyntaxKind['JSDocReadonlyTag'] = 319] = 'JSDocReadonlyTag';
    SyntaxKind[SyntaxKind['JSDocCallbackTag'] = 320] = 'JSDocCallbackTag';
    SyntaxKind[SyntaxKind['JSDocEnumTag'] = 321] = 'JSDocEnumTag';
    SyntaxKind[SyntaxKind['JSDocParameterTag'] = 322] = 'JSDocParameterTag';
    SyntaxKind[SyntaxKind['JSDocReturnTag'] = 323] = 'JSDocReturnTag';
    SyntaxKind[SyntaxKind['JSDocThisTag'] = 324] = 'JSDocThisTag';
    SyntaxKind[SyntaxKind['JSDocTypeTag'] = 325] = 'JSDocTypeTag';
    SyntaxKind[SyntaxKind['JSDocTemplateTag'] = 326] = 'JSDocTemplateTag';
    SyntaxKind[SyntaxKind['JSDocTypedefTag'] = 327] = 'JSDocTypedefTag';
    SyntaxKind[SyntaxKind['JSDocPropertyTag'] = 328] = 'JSDocPropertyTag';
    // Synthesized list
    SyntaxKind[SyntaxKind['SyntaxList'] = 329] = 'SyntaxList';
    // Transformation nodes
    SyntaxKind[SyntaxKind['NotEmittedStatement'] = 330] = 'NotEmittedStatement';
    SyntaxKind[SyntaxKind['PartiallyEmittedExpression'] = 331] = 'PartiallyEmittedExpression';
    SyntaxKind[SyntaxKind['CommaListExpression'] = 332] = 'CommaListExpression';
    SyntaxKind[SyntaxKind['MergeDeclarationMarker'] = 333] = 'MergeDeclarationMarker';
    SyntaxKind[SyntaxKind['EndOfDeclarationMarker'] = 334] = 'EndOfDeclarationMarker';
    SyntaxKind[SyntaxKind['SyntheticReferenceExpression'] = 335] = 'SyntheticReferenceExpression';
    // Enum value count
    SyntaxKind[SyntaxKind['Count'] = 336] = 'Count';
    // Markers
    SyntaxKind[SyntaxKind['FirstAssignment'] = 62] = 'FirstAssignment';
    SyntaxKind[SyntaxKind['LastAssignment'] = 77] = 'LastAssignment';
    SyntaxKind[SyntaxKind['FirstCompoundAssignment'] = 63] = 'FirstCompoundAssignment';
    SyntaxKind[SyntaxKind['LastCompoundAssignment'] = 77] = 'LastCompoundAssignment';
    SyntaxKind[SyntaxKind['FirstReservedWord'] = 80] = 'FirstReservedWord';
    SyntaxKind[SyntaxKind['LastReservedWord'] = 115] = 'LastReservedWord';
    SyntaxKind[SyntaxKind['FirstKeyword'] = 80] = 'FirstKeyword';
    SyntaxKind[SyntaxKind['LastKeyword'] = 155] = 'LastKeyword';
    SyntaxKind[SyntaxKind['FirstFutureReservedWord'] = 116] = 'FirstFutureReservedWord';
    SyntaxKind[SyntaxKind['LastFutureReservedWord'] = 124] = 'LastFutureReservedWord';
    SyntaxKind[SyntaxKind['FirstTypeNode'] = 171] = 'FirstTypeNode';
    SyntaxKind[SyntaxKind['LastTypeNode'] = 192] = 'LastTypeNode';
    SyntaxKind[SyntaxKind['FirstPunctuation'] = 18] = 'FirstPunctuation';
    SyntaxKind[SyntaxKind['LastPunctuation'] = 77] = 'LastPunctuation';
    SyntaxKind[SyntaxKind['FirstToken'] = 0] = 'FirstToken';
    SyntaxKind[SyntaxKind['LastToken'] = 155] = 'LastToken';
    SyntaxKind[SyntaxKind['FirstTriviaToken'] = 2] = 'FirstTriviaToken';
    SyntaxKind[SyntaxKind['LastTriviaToken'] = 7] = 'LastTriviaToken';
    SyntaxKind[SyntaxKind['FirstLiteralToken'] = 8] = 'FirstLiteralToken';
    SyntaxKind[SyntaxKind['LastLiteralToken'] = 14] = 'LastLiteralToken';
    SyntaxKind[SyntaxKind['FirstTemplateToken'] = 14] = 'FirstTemplateToken';
    SyntaxKind[SyntaxKind['LastTemplateToken'] = 17] = 'LastTemplateToken';
    SyntaxKind[SyntaxKind['FirstBinaryOperator'] = 29] = 'FirstBinaryOperator';
    SyntaxKind[SyntaxKind['LastBinaryOperator'] = 77] = 'LastBinaryOperator';
    SyntaxKind[SyntaxKind['FirstStatement'] = 229] = 'FirstStatement';
    SyntaxKind[SyntaxKind['LastStatement'] = 245] = 'LastStatement';
    SyntaxKind[SyntaxKind['FirstNode'] = 156] = 'FirstNode';
    SyntaxKind[SyntaxKind['FirstJSDocNode'] = 298] = 'FirstJSDocNode';
    SyntaxKind[SyntaxKind['LastJSDocNode'] = 328] = 'LastJSDocNode';
    SyntaxKind[SyntaxKind['FirstJSDocTagNode'] = 310] = 'FirstJSDocTagNode';
    SyntaxKind[SyntaxKind['LastJSDocTagNode'] = 328] = 'LastJSDocTagNode';
        /* @internal */ SyntaxKind[SyntaxKind['FirstContextualKeyword'] = 125] = 'FirstContextualKeyword';
        /* @internal */ SyntaxKind[SyntaxKind['LastContextualKeyword'] = 155] = 'LastContextualKeyword';
})(x);

assert.strictEqual(x['FirstNode'], 156);