<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
    <AssemblyName>YantraJS.Core</AssemblyName>
    <PackageId>YantraJS.Core</PackageId>
    <PackageTags>yantra,yantrajs,javascript,c#,standard,core,framework,.net</PackageTags>
    <Description>JavaScript Engine Core for .NET Standard</Description>
    <PackageProjectUrl>http://yantrajs.com/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/yantrajs/yantra</RepositoryUrl>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <Version>1.0.1</Version>
	  <LangVersion>latest</LangVersion>
	  <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
	  <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	  <IncludeSymbols>true</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  <EmbedAllSources>True</EmbedAllSources>
	  <DebugType>embedded</DebugType>
       <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

	<!-- Run code generation right before the CoreCompile step -->
	<Target Name="RunRoslynParser" BeforeTargets="CoreCompile">
		<PropertyGroup>
			<!-- Define the relative or absolute path to your parser executable -->
			<ParserExePath>$(SolutionDir)YantraJS.JSClassGenerator\bin\Debug\net8.0\YantraJS.JSClassGenerator.exe</ParserExePath>
		</PropertyGroup>

		<Message Importance="high" Text="[Pre-Build] Executing Roslyn Parser Engine..." />

		<!-- Execute the console app. Pass project directory as an argument if needed -->
		<Exec Command="&quot;$(ParserExePath)&quot; &quot;YantraJS.Core&quot; &quot;$(ProjectDir).&quot; &quot;$(ProjectDir)Generated&quot;" 
			  ContinueOnError="WarnAndContinue"/>
	</Target>
	
  
  <ItemGroup>
    <PackageReference Include="ErrorProne.NET.Structs" Version="0.3.0-beta.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.9.50">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1' ">
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YantraJS.ExpressionCompiler\YantraJS.ExpressionCompiler.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Microsoft.Build.Tasks.v4.0">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Microsoft.Build.Tasks.v4.0.dll</HintPath>
    </Reference>
  </ItemGroup>
  
</Project>
